#!/bin/bash

mkdir -p ~/bin

ln -sfv `pwd`/repo ~/bin/repo

chmod +x `pwd`/repo

echo "All set. Go to a git repository and try 'repo' to see usage examples."
echo "If the command is not recognised ensure that the ~/bin directory is in your PATH."
